INSERT INTO status (status_title) VALUES ('New');
INSERT INTO status (status_title) VALUES ('In Progress');
INSERT INTO status (status_title) VALUES ('Complete');
INSERT INTO status (status_title) VALUES ('Reset');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Original Series', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Original Series', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Original Series', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Animated Series', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Animated Series', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 4, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 5, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 6, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: The Next Generation', 7, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 4, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 5, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 6, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Deep Space Nine', 7, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 4, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 5, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 6, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Voyager', 7, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Enterprise', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Enterprise', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Enterprise', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Enterprise', 4, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Discovery', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Discovery', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Discovery', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Discovery', 4, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Discovery', 5, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Picard', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Picard', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Picard', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Lower Decks', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Lower Decks', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Lower Decks', 3, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Lower Decks', 4, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Prodigy', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Prodigy', 2, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Strange New Worlds', 1, 'SEMA');
INSERT INTO season (series, season, stapi_season_id) VALUES ('Star Trek: Strange New Worlds', 2, 'SEMA');
INSERT INTO user (user_name, first_name, last_name, last_login) VALUES ('admin', 'Alice', 'Admin', null);
INSERT INTO user (user_name, first_name, last_name, last_login) VALUES ('badmin', 'Bob', 'Admin', null);
INSERT INTO user (user_name, first_name, last_name, last_login) VALUES ('cadmin', 'Charlie', 'Admin', null);
INSERT INTO user (user_name, first_name, last_name, last_login) VALUES ('dadmin', 'Dave', 'Admin', null);
INSERT INTO own (user_id, season_id) VALUES (1, 1);
INSERT INTO own (user_id, season_id) VALUES (1, 2);
INSERT INTO own (user_id, season_id) VALUES (1, 3);
INSERT INTO own (user_id, season_id) VALUES (2, 4);
INSERT INTO own (user_id, season_id) VALUES (2, 5);
INSERT INTO own (user_id, season_id) VALUES (3, 6);
INSERT INTO own (user_id, season_id) VALUES (3, 7);
INSERT INTO own (user_id, season_id) VALUES (3, 8);
INSERT INTO own (user_id, season_id) VALUES (3, 9);
INSERT INTO own (user_id, season_id) VALUES (3, 10);
INSERT INTO own (user_id, season_id) VALUES (3, 11);
INSERT INTO own (user_id, season_id) VALUES (3, 12);
INSERT INTO own (user_id, season_id) VALUES (4, 13);
INSERT INTO own (user_id, season_id) VALUES (4, 14);
INSERT INTO own (user_id, season_id) VALUES (4, 15);
INSERT INTO own (user_id, season_id) VALUES (4, 16);
INSERT INTO own (user_id, season_id) VALUES (4, 17);
INSERT INTO own (user_id, season_id) VALUES (4, 18);
INSERT INTO own (user_id, season_id) VALUES (4, 19);
INSERT INTO episode (title, stapi_episode_id, season_id) VALUES ('Emissary', 'EPMA', 13);
INSERT INTO episode (title, stapi_episode_id, season_id) VALUES ('The Homecoming', 'EPMA', 14);
INSERT INTO episode (title, stapi_episode_id, season_id) VALUES ('The Search', 'EPMA', 15);
INSERT INTO episode (title, stapi_episode_id, season_id) VALUES ('The Way of the Warrior', 'EPMA', 16);
INSERT INTO view (view_date, user_id, episode_id, status_id) VALUES (NOW(), 1, 1, 1);
INSERT INTO view (view_date, user_id, episode_id, status_id) VALUES (NOW(), 2, 2, 1);
INSERT INTO view (view_date, user_id, episode_id, status_id) VALUES (NOW(), 3, 3, 2);
INSERT INTO view (view_date, user_id, episode_id, status_id) VALUES (NOW(), 4, 4, 3);